eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: trend-trading-backtest-service

#feign.hystrix.enabled: true  用于开启 feign 模式的断路器
#使用feign模式可以从其他微服务中获取数据
feign.hystrix.enabled: true