#微服务的名称
spring:
  application:
    name: index-codes-service
  #配置链路追踪zipkin
  zipkin:
    base-url: http://localhost:9411
  #注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/