spring:
  application:
    name: trend-trading-backtest-view
  #配置链路追踪zipkin
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

#允许访问：/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"